version: "3.0"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint:
      - /app/docker_script.sh
