"""empty message

Revision ID: f363f7332d82
Revises: 2ee056cc0838
Create Date: 2019-02-10 22:59:36.576983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f363f7332d82'
down_revision = '2ee056cc0838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demoObject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demoObject_name'), 'demoObject', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demoObject_name'), table_name='demoObject')
    op.drop_table('demoObject')
    # ### end Alembic commands ###
